"""initial_schema

Revision ID: 9d15fb35abdf
Revises: 
Create Date: 2026-08-06 14:08:22.103611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d15fb35abdf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('destination', sa.String(length=30), nullable=False),
    sa.Column('abbr', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbr'),
    sa.UniqueConstraint('origin', 'destination', name='uq_route_origin_destination')
    )
    op.create_table('route_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_history')
    op.drop_table('route')
    # ### end Alembic commands ###
