"""initial revision

Revision ID: e36b51ccf9b4
Revises: 
Create Date: 2026-03-25 16:53:13.890777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36b51ccf9b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.create_unique_constraint(None, 'route', ['abbr'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route', type_='unique')
    op.create_table('test',

    )
    # ### end Alembic commands ###
