"""departure_date column

Revision ID: 5c6ff7e4c0fb
Revises: e36b51ccf9b4
Create Date: 2026-03-26 12:39:32.632311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6ff7e4c0fb'
down_revision: Union[str, Sequence[str], None] = 'e36b51ccf9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_history', sa.Column('departure_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_history', 'departure_date')
    # ### end Alembic commands ###
